CREATE TABLE ENTRADA (
Numero_da_entrada INT PRIMARY KEY,
ID_visitante INT,
ID_parque INT,
ID_funcionario INT
);

CREATE TABLE VISITANTE (
Nome VARCHAR(50),
Data_de_nascimento DATE,
ID_visitante INT PRIMARY KEY
);

CREATE TABLE FUNCIONARIO (
ID_funcionario INT PRIMARY KEY,
Nome VARCHAR(50),
Logradouro VARCHAR(50),
Complemento VARCHAR(50),
Titulo VARCHAR(50),
ID_parque INT
);

CREATE TABLE PARQUE_ECOLOGICO (
Nome VARCHAR(50),
Localizacao VARCHAR(50),
ID_parque INT PRIMARY KEY
);

CREATE TABLE EXCURSAO (
ID_parque INT,
ID_excursao INT PRIMARY KEY,
Data_exc DATETIME,
FOREIGN KEY(ID_parque) REFERENCES PARQUE_ECOLOGICO (ID_parque)
);

CREATE TABLE AREA (
ID_area INT PRIMARY KEY,
Nome VARCHAR(50),
Dimensao INT,
ID_parque INT,
FOREIGN KEY(ID_parque) REFERENCES PARQUE_ECOLOGICO (ID_parque)
);

CREATE TABLE PROJETO (
ID_projeto INT PRIMARY KEY,
Titulo VARCHAR(50)
);

CREATE TABLE ESPECIE (
ID_especie INT PRIMARY KEY,
Nome_cientifico VARCHAR(50),
Nome_popular VARCHAR(50)
);

CREATE TABLE Telefone_FUNC (
id_telf INT,
Telefone VARCHAR(50),
FOREIGN KEY(Id_telf) REFERENCES FUNCIONARIO (ID_funcionario)
);

CREATE TABLE Telefone_PQ (
id_telp INT,
Telefone VARCHAR(50),
FOREIGN KEY(id_telp) REFERENCES PARQUE_ECOLOGICO (ID_parque)
);

CREATE TABLE PERTENCE (
ID_visitante INT,
ID_excursao INT,
FOREIGN KEY(ID_visitante) REFERENCES VISITANTE (ID_visitante),
FOREIGN KEY(ID_excursao) REFERENCES EXCURSAO (ID_excursao)
);

CREATE TABLE MANTIDA_POR (
ID_area INT,
ID_funcionario INT,
FOREIGN KEY(ID_area) REFERENCES AREA (ID_area),
FOREIGN KEY(ID_funcionario) REFERENCES FUNCIONARIO (ID_funcionario)
);

CREATE TABLE CONTEM (
ID_area INT,
ID_especie_contem INT,
FOREIGN KEY(ID_area) REFERENCES AREA (ID_area),
FOREIGN KEY(ID_especie_contem) REFERENCES ESPECIE (ID_especie)
);

CREATE TABLE ESTUDADA (
ID_especie_estudada INT,
ID_projeto INT,
FOREIGN KEY(ID_especie_estudada) REFERENCES ESPECIE (ID_especie),
FOREIGN KEY(ID_projeto) REFERENCES PROJETO (ID_projeto)
);

CREATE TABLE REALIZA (
ID_projeto INT,
ID_funcionario INT,
FOREIGN KEY(ID_projeto) REFERENCES PROJETO (ID_projeto),
FOREIGN KEY(ID_funcionario) REFERENCES FUNCIONARIO (ID_funcionario)
);

CREATE TABLE VIGIADA_POR (
ID_funcionario INT,
ID_area INT,
FOREIGN KEY(ID_funcionario) REFERENCES FUNCIONARIO (ID_funcionario),
FOREIGN KEY(ID_area) REFERENCES AREA (ID_area)
);

ALTER TABLE ENTRADA ADD FOREIGN KEY(ID_visitante) REFERENCES VISITANTE(ID_visitante);
ALTER TABLE ENTRADA ADD FOREIGN KEY(ID_parque) REFERENCES PARQUE_ECOLOGICO(ID_parque);
ALTER TABLE ENTRADA ADD FOREIGN KEY(ID_funcionario) REFERENCES FUNCIONARIO(ID_funcionario);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY(ID_parque) REFERENCES PARQUE_ECOLOGICO(ID_parque);

